[project]
name = "texcv"
version = "0.1.0"
description = "CLI tool to generate LaTeX CVs from YAML"
authors = [
    { name = "Keeththigan" }
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "pyyaml",
    "jinja2",
    "typer"
]

[project.scripts]
texcv = "texcv.cli:app"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"